config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  root 'home#index'

  resources :establishments

  resources :reports

  resources :users

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_admin!
  before_action :setup_firebase

  def setup_firebase
  	base_uri = 'https://hb141-2fc0d.firebaseio.com/'
	@firebase = Firebase::Client.new(base_uri)
  end
end

app/controllers/establishments_controller.rb
require 'date'

class EstablishmentsController < ApplicationController

	def index
		establishments = @firebase.get('/establishment/').body

		establishments_with_status = {}

		establishments.each do |id, establishment|
			reports = @firebase.get('/report/').body
			reports.keep_if do |r_id, report|
				report["EID"].to_s == id
			end
			establishment["Status"] = status(reports)
			establishments_with_status[id] = establishment
		end

		@establishments = establishments_with_status
	end

	def show
		@establishment = @firebase.get('/establishment/' + params[:id]).body

		reports = @firebase.get('/report/').body
		reports.keep_if do |id, report|
			report["EID"].to_s == params[:id]
		end

		@reports = reports
	end

	def edit
		@establishment = @firebase.get('/establishment/' + params[:id]).body

		@manager = firebase.get('/manager/' + @establishment["MID"].to_s).body
	end

	def update
		establishment = @firebase.get('/establishment/' + params[:id]).body

		update_establishment = firebase.update('/establishment/' + params[:id], {
				"Name" => params["Name"],
				"Address" => params["Address"],
				"Phone Number" => params["Phone Number"],
				"Website" => params["Website"]
			})

		redirect_to establishment_path(params[:id])
	end

	def destroy
		reports = @firebase.get('/report/').body
		reports.each do |id, report|
			if report["EID"].to_s == params[:id]
				@firebase.delete('/report/' + id)
			end
		end

		@firebase.delete('/establishment/' + params[:id])

		redirect_to establishments_path
	end

	private

	def status(reports)
		neg_reports = 0
		latest_report = DateTime.new(0)

		reports.each do |id, report|
			if pass(report)
				return "COMPLIES"
			end
			if neg_reports < 4 and not pass(report)
				neg_reports += 1
			end
			begin
				datetime = DateTime.strptime(report["Datetime"], '%m/%d/%y %H:%M %p')
			rescue
				datetime = DateTime.new(0)
			end
			if datetime > latest_report
				latest_report = datetime
			end
		end

		if latest_report < DateTime.now - 30
			return "NEEDS VISIT"
		end

		return neg_reports.ordinalize.upcase + " NEGATIVE SURVEY"
	end

	def pass(report)
		report["Public View"] and report["Restroom View"] and not report["No View"]
	end

	helper_method :status, :pass
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :authenticate_admin!
	skip_before_action :setup_firebase
	
	def index
	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

	def index
		@reports = @firebase.get('/report/').body
	end

	def show
		@report = @firebase.get('/report/' + params[:id]).body

		@establishment = @firebase.get('/establishment/' + @report["EID"].to_s).body

		#@volunteer = firebase.get('/volunteer/' + @report["VID"].to_s).body
	end

	def edit
		@report = @firebase.get('/report/' + params[:id]).body
	end

	def update
		report = @firebase.get('/report/' + params[:id]).body

		update_report = @firebase.update('/report/' + params[:id], {
				"Datetime" => params["Datetime"],
				"Comment" => params["Comment"],
				"Public View" => params["Public View"] ? true : false,
				"Restroom View" => params["Restroom View"] ? true : false,
				"No View" => params["No View"] ? true : false
			})

		redirect_to report_path(params[:id])
	end

	def destroy
		@firebase.delete('/report/' + params[:id])

		redirect_to reports_path		
	end

	private

	def pass(report)
		report["Public View"] and report["Restroom View"] and not report["No View"]
	end

	helper_method :pass
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = Array.new
	end

	def show
		@user = nil
	end

	def edit
	end

	def update
	end

	def destroy
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/establishments/edit.html.erb
<div class="page-header">
	<h2>Edit Establishment</h2>
	<ul class="actions">
		<li><%= link_to "Back", establishment_path(params[:id]), class: "btn btn-primary" %></li>
	</ul>
</div>

<%= form_tag establishment_path(params[:id]), method: :put do %>
<div class="container">
	<p>
		<%= label_tag "Name" %>
		<%= text_field_tag "Name", @establishment["Name"] %>
	</p>
	<p>
		<%= label_tag "Address" %>
		<%= text_field_tag "Address", @establishment["Address"] %>
	</p>
	<p>
		<%= label_tag "Phone Number" %>
		<%= text_field_tag "Phone Number", @establishment["Phone Number"] %>
	</p>
	<p>
		<%= label_tag "Website" %>
		<%= text_field_tag "Website", @establishment["Website"] %>
	</p>
	<%= submit_tag "Edit Establishment", class: "btn btn-primary" %>
</div>
<% end %>

app/views/establishments/index.html.erb
<div class="page-header">
<h2>Establishments</h2>
<ul class="actions">
</ul>
</div>

<div class="container">
<div class="table-responsive">
<table id="establishments" class="table table-bordered">
	<thead>
		<td>Name</td>
		<td>Location</td>
		<td>Status</td>
		<td></td>
	</thead>
	<% @establishments.each do |id, establishment| %>
		<% status = case establishment["Status"]
					  when "COMPLIES" 			 then "success"
		              when "NEEDS VISIT" 		 then "warning"
		              when "1ST NEGATIVE SURVEY" then "danger"
		              when "2ND NEGATIVE SURVEY" then "danger"
		              when "3RD NEGATIVE SURVEY" then "danger"
		              when "4TH NEGATIVE SURVEY" then "danger"
		              else 							  ""
					end %>
		<tr class=<%= status %>>
			<td><%= establishment["Name"] %></td>
			<td><%= establishment["Address"] %></td>
			<td><%= establishment["Status"] %></td>
			<td><%= link_to "View", establishment_path(id), class: "btn btn-primary" %></td>
		</tr>
	<% end %>
</table>
</div>
</div>

app/views/establishments/show.html.erb
<div class="page-header">
	<h2>
		<%= @establishment["Name"] %>
		<% status = case status(@reports)
					  when "COMPLIES" 			 then "success"
		              when "NEEDS VISIT" 		 then "warning"
		              when "1ST NEGATIVE SURVEY" then "danger"
		              when "2ND NEGATIVE SURVEY" then "danger"
		              when "3RD NEGATIVE SURVEY" then "danger"
		              when "4TH NEGATIVE SURVEY" then "danger"
		              else 							  "primary"
					end %>
		<span style="font-size: 14px;" class=<%= ('"label label-' + status + '"').html_safe %>><%= status(@reports) %></span>
	</h2>

	<ul class="actions">
		<li><%= link_to "Back", establishments_path, class: "btn btn-primary" %></li>
		<li><%= link_to "Edit Establishment", edit_establishment_path(params[:id]), class: "btn btn-warning" %></li>
		<li><%= link_to "Delete Establishment", establishment_path(params[:id]), method: :delete, data: { confirm: "Are you sure you want to delete this establishment and all associated reports?" }, class: "btn btn-danger" %></li>
	</ul>
</div>

<div class="container">
<p><%= @establishment["Address"] %></p>
<p>Phone:
	<% if @establishment["Phone Number"] == nil %> 
		N/A
	<% else %>
		<a href=<%= 'tel:' + @establishment["Phone Number"].gsub(/\s+/, "") %>><%= @establishment["Phone Number"] %></a>
	<% end %>
</p>

<p>Website:
	<% if @establishment["Website"] == nil %>
		N/A
	<% else %> 
		<a href=<%= @establishment["Website"] %>><%= @establishment["Website"] %></a>
	<% end %>
</p>

<div class="table-responsive">
	<h3>Reports About <%= @establishment["Name"] %></h3>
	<table class="table table-bordered">
		<thead>
			<td>ID</td>
			<td>Submitted On</td>
			<td>Comment</td>
			<td></td>
		</thead>
		<% @reports.each do |id, report| %>
			<tr class=<%= pass(report) ? "success" : "danger" %>>
				<td><%= id %></td>
				<td><%= report["Datetime"] %></td>
				<td><%= report["Comment"] %></td>
				<td><%= link_to "View", report_path(id), class: "btn btn-primary" %></td>
			</tr>
		<% end %>
	</table>
</div>
</div>

app/views/home/index.html.erb
<h2>Welcome to the HB141 Admin Portal!</h2>
	<ul class="list-unstyled list-inline">
		<% unless admin_signed_in? %>
			<li><%= link_to "Sign In", new_admin_session_path, class: "btn btn-lg btn-primary" %></li>
		<% end %>

		<% if admin_signed_in? %>				
			<li><%= link_to "Create New Admin", new_admin_registration_path, class: "btn btn-lg btn-primary" %></li>
			<li><%= link_to "Establishments", establishments_path, class: "btn btn-lg btn-primary" %></li>
			<li><%= link_to "Reports", reports_path, class: "btn btn-lg btn-primary" %></li>
			<li><%= link_to "Users", users_path, class: "btn btn-lg btn-primary" %></li>
		<% end %>
	</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HB141 Admin Portal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "HB141 Admin Portal", root_path, class: "navbar-brand" %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="collapse">
        <ul class="nav navbar-nav">
          <li class="<%= "active" if current_page?("/") %>">
            <%= link_to "Home", root_path %>
          </li>
          <% unless admin_signed_in? %>
            <li class="<%= "active" if current_page?("/admins/sign_in") %>">
              <%= link_to "Sign in", new_admin_session_path %>
            </li>
          <% end %>
          <% if admin_signed_in? %>
          	<li class="<%= "active" if current_page?("/establishments") %>">
              <%= link_to "Establishments", establishments_path %>
            </li>
            <li class="<%= "active" if current_page?("/reports") %>">
              <%= link_to "Reports", reports_path %>
            </li>
          <% end %>
        </ul>
        <% if admin_signed_in? %>
          <div class="navbar-right">
            <p class="navbar-text">
              Signed in as <%= current_admin.email %>.
            </p>
            <ul class="nav navbar-nav">
              <li><%= link_to "Sign out", destroy_admin_session_path, method: :delete %></li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </nav>

<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/reports/edit.html.erb
<div class="page-header">
	<h2>Edit Report</h2>
	<ul class="actions">
		<li><%= link_to "Back", report_path(params[:id]), class: "btn btn-primary" %></li>
	</ul>
</div>

<%= form_tag report_path(params[:id]), method: :put do %>
<div class="container">
	<p>
		<%= label_tag "Datetime" %>
		<%= text_field_tag "Datetime", @report["Datetime"] %>
	</p>
	<p>
		<%= label_tag "Comment" %>
		<%= text_field_tag "Comment", @report["Comment"] %>
	</p>
	<p>
		<%= label_tag "Public View" %>
		<%= check_box_tag "Public View", true, @report["Public View"] %>
	</p>
	<p>
		<%= label_tag "Restroom View" %>
		<%= check_box_tag "Restroom View", true, @report["Restroom View"] %>
	</p>
	<p>
		<%= label_tag "No View" %>
		<%= check_box_tag "No View", true, @report["No View"] %>
	</p>
	<%= submit_tag "Edit Report", class: "btn btn-primary" %>
</div>
<% end %>

app/views/reports/index.html.erb
<div class="page-header">
<h2>Reports</h2>
<ul class="actions">
</ul>
</div>

<div class="container">
<div class="table-responsive">
<table id="establishments" class="table table-bordered">
	<thead>
		<td>ID</td>
		<td>Submitted On</td>
		<td>Comment</td>
		<td></td>
	</thead>
	<% @reports.each do |id, report| %>
		<tr class=<%= pass(report) ? "success" : "danger" %>>
			<td><%= id %></td>
			<td><%= report["Datetime"] %></td>
			<td><%= report["Comment"] %></td>
			<td><%= link_to "View", report_path(id), class: "btn btn-primary" %></td>
		</tr>
	<% end %>
</table>
</div>
</div>

app/views/reports/show.html.erb
<div class="page-header">
	<h2>
		Report #<%= params[:id] %>
		<span style="font-size: 14px;" class=<%= ('"label label-' + (pass(@report) ? "success" : "danger") + '"').html_safe %>><%= pass(@report) ? "Positive" : "Negative" %> Report</span>
	</h2>

	<ul class="actions">
		<li><%= link_to "Back", reports_path, class: "btn btn-primary" %></li>
		<li><%= link_to "Edit Report", edit_report_path(params[:id]), class: "btn btn-warning" %></li>
		<li><%= link_to "Delete Report", report_path(params[:id]), method: :delete, data: { confirm: "Are you sure you want to delete this report?" }, class: "btn btn-danger" %></li>
	</ul>
</div>

<div class="container">
	<h3>Reported On <%= link_to @establishment["Name"], establishment_path(@report["EID"]) %></h3>
	<div class="well well-lg">
		<h4><%= @report["Comment"] %></h4>
	</div>
	<p>Submitted On <%= @report["Datetime"] %></p>
	<p>Submitted By <%= @report ["VID"] %></p>
</div>

app/views/users/index.html.erb
<div class="page-header">
<h2>Users</h2>
<ul class="actions">
</ul>
</div>

<div class="container">
<div class="table-responsive">
<table id="establishments" class="table table-bordered">
	<thead>
		<td>ID</td>
		<td>Name</td>
		<td>Email</td>
		<td></td>
	</thead>
	<% @users.each do |id, user| %>
		<tr>
			<td><%= id %></td>
			<td><%= user["Name"] %></td>
			<td><%= user["Email"] %></td>
			<td><%= link_to "View", user_path(id), class: "btn btn-primary" %></td>
		</tr>
	<% end %>
</table>
</div>
</div>